# 第一次修改语言文件,需重启生效
language: zh_CN

# 子服标识，群组服需先配置这个
server: "lobby"

# 子服自定义名称
# 可以用 papi变量 %playerChat_server_name% 读取 或者内部变量 ${serverName} 读取
serverName: ""

# /plc tell 指令的简写
tellAlias:
  - "/tell"
  - "/msg"

# 玩家第一次登录后的默认频道
# 注意 如果修改为其他频道,请把对应的权限提前给予 查看: playerChat.chat.频道名 使用: playerChat.use.频道名
firstLoginChatDefault: "default"

# 是否开启 AI 审核
ai:
  enable: false
  chatMaxCount: 3
  voteMaxNumber: 5
  command:
    - "/lb xxx xxx"
    - "/ban xxx xxx"

# 聊天冷却时间(单位秒)(可无限扩展和修改子节点，权限格式: playerChat.chatTime.vip1)
# 0为关闭状态
chatTime:
  # 默认玩家的时间
  default: 0
  # vip1的上限 需要权限 playerWarp.delayTime.vip1
  vip1: 0
  # vip2的上限 需要权限 playerWarp.delayTime.vip2
  vip2: 0
  # vip3的上限 需要权限 playerWarp.delayTime.vip3
  vip3: 0

# 聊天黑名单
blacklist:
  - '操'
  - '草'
  - 'cao'
  - '%'

# 是否开启更新提醒,建议开启
isCheckUpdate: true

# op登录时候是否发送更新提醒
isCheckUpdateToOpMsg: true